### ISSUE TITLE
i18n requirements

### ISSUE THREAD

**Issue by Nikschavan** [brainstormforce/bb-bootstrap-alerts#1]
- Mention `Text Domain` in plugin header - [More info](https://codex.wordpress.org/I18n_for_WordPress_Developers#Text_Domains)
- Make the plugin text domain `bb-bootstrap-alerts` 
- Make sure this text domain is used in all the strings in the plugin [Eg link](https://github.com/brainstormforce/bb-bootstrap-alerts/blob/master/bb-bootstrap-alerts-module/bb-bootstrap-alerts-module.php#L7)
- All the strings should be passed through gettext functions, eg `__()`, `_e()` etc. [Eg](https://github.com/brainstormforce/bb-bootstrap-alerts/blob/master/bb-bootstrap-alerts-module/bb-bootstrap-alerts-module.php#L80)
- Load the plugin [text domain](https://codex.wordpress.org/Function_Reference/load_plugin_textdomain)

**Comment by akashdbsf** [comment]
Mentioned `Text Domain ` in plugin header.
Changed plugin domain to `bb-bootstrap-alerts`.
Checked for text domain is for all string.
All strings are passed in ` __()` function.

**Comment by Nikschavan** [comment]
@akashdbsf 
Remaining - 

- Load the plugin [text domain](https://codex.wordpress.org/Function_Reference/load_plugin_textdomain)
